version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - echo Build completed
      - mv target/marketplace-0.0.1-SNAPSHOT.jar marketplace-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - marketplace-0.0.1-SNAPSHOT.jar